In [1]:
import pandas as pd

In [8]:
data = pd.read_csv("abalone.data")
target = pd.read_fwf("abalone.names")

In [9]:
data.head(5)
target.head(5)

1. Title of Database: Abalone data
0                                        2. Sources:
1                   (a) Original owners of database:
2                          Marine Resources Division
3             Marine Research Laboratories - Taroona
4  Department of Primary Industry and Fisheries, ...

In [13]:
data.describe()

0.455        0.365        0.095        0.514      0.2245  \
count  4176.000000  4176.000000  4176.000000  4176.000000  4176.00000   
mean      0.524009     0.407892     0.139527     0.828818     0.35940   
std       0.120103     0.099250     0.041826     0.490424     0.22198   
min       0.075000     0.055000     0.000000     0.002000     0.00100   
25%       0.450000     0.350000     0.115000     0.441500     0.18600   
50%       0.545000     0.425000     0.140000     0.799750     0.33600   
75%       0.615000     0.480000     0.165000     1.153250     0.50200   
max       0.815000     0.650000     1.130000     2.825500     1.48800   

             0.101         0.15           15  
count  4176.000000  4176.000000  4176.000000  
mean      0.180613     0.238852     9.932471  
std       0.109620     0.139213     3.223601  
min       0.000500     0.001500     1.000000  
25%       0.093375     0.130000     8.000000  
50%       0.171000     0.234000     9.000000  
75%       0.253000     0.329000    11.000000  
max       0.760000     1.005000    29.000000

In [14]:
data.dtypes

M          object
0.455     float64
0.365     float64
0.095     float64
0.514     float64
0.2245    float64
0.101     float64
0.15      float64
15          int64
dtype: object

In [24]:
data1,data2 = data.iloc[:,1:3],data.iloc[:,3:]
data2

0.095   0.514  0.2245   0.101    0.15  15
0     0.090  0.2255  0.0995  0.0485  0.0700   7
1     0.135  0.6770  0.2565  0.1415  0.2100   9
2     0.125  0.5160  0.2155  0.1140  0.1550  10
3     0.080  0.2050  0.0895  0.0395  0.0550   7
4     0.095  0.3515  0.1410  0.0775  0.1200   8
...     ...     ...     ...     ...     ...  ..
4171  0.165  0.8870  0.3700  0.2390  0.2490  11
4172  0.135  0.9660  0.4390  0.2145  0.2605  10
4173  0.205  1.1760  0.5255  0.2875  0.3080   9
4174  0.150  1.0945  0.5310  0.2610  0.2960  10
4175  0.195  1.9485  0.9455  0.3765  0.4950  12

[4176 rows x 6 columns]

In [25]:
import tensorflow as tf
data1 = data1.astype('float64')
X,y = tf.constant(data1.values),tf.constant(data2.values)

In [26]:
X

<tf.Tensor: shape=(4176, 2), dtype=float64, numpy=
array([[0.35 , 0.265],
       [0.53 , 0.42 ],
       [0.44 , 0.365],
       ...,
       [0.6  , 0.475],
       [0.625, 0.485],
       [0.71 , 0.555]])>

In [27]:
y

<tf.Tensor: shape=(4176, 6), dtype=float64, numpy=
array([[ 0.09  ,  0.2255,  0.0995,  0.0485,  0.07  ,  7.    ],
       [ 0.135 ,  0.677 ,  0.2565,  0.1415,  0.21  ,  9.    ],
       [ 0.125 ,  0.516 ,  0.2155,  0.114 ,  0.155 , 10.    ],
       ...,
       [ 0.205 ,  1.176 ,  0.5255,  0.2875,  0.308 ,  9.    ],
       [ 0.15  ,  1.0945,  0.531 ,  0.261 ,  0.296 , 10.    ],
       [ 0.195 ,  1.9485,  0.9455,  0.3765,  0.495 , 12.    ]])>