In [3]:
import numpy as np
A = np.random.randn(5)  ## rank 1 array  // don't use this shape of array in future
print(A)

[-1.31600446  0.60882733 -0.17180406 -0.91489499  0.20808503]


In [4]:
print(A.shape)

(5,)


In [5]:
print(A.T)

[-1.31600446  0.60882733 -0.17180406 -0.91489499  0.20808503]


In [6]:
A = np.random.randn(5,1)
print(A)

[[ 0.11942128]
 [-0.53079616]
 [-1.04732835]
 [ 0.28005047]
 [ 0.09818404]]


In [7]:
print(A.T)

[[ 0.11942128 -0.53079616 -1.04732835  0.28005047  0.09818404]]


In [8]:
print(A.shape)

(5, 1)


In [11]:
print(np.dot(A,A.T))

[[ 0.01426144 -0.06338836 -0.12507329  0.03344399  0.01172526]
 [-0.06338836  0.28174456  0.55591787 -0.14864972 -0.05211571]
 [-0.12507329  0.55591787  1.09689667 -0.2933048  -0.10283093]
 [ 0.03344399 -0.14864972 -0.2933048   0.07842827  0.02749649]
 [ 0.01172526 -0.05211571 -0.10283093  0.02749649  0.00964011]]


In [13]:
A*A.T

array([[ 0.01426144, -0.06338836, -0.12507329,  0.03344399,  0.01172526],
       [-0.06338836,  0.28174456,  0.55591787, -0.14864972, -0.05211571],
       [-0.12507329,  0.55591787,  1.09689667, -0.2933048 , -0.10283093],
       [ 0.03344399, -0.14864972, -0.2933048 ,  0.07842827,  0.02749649],
       [ 0.01172526, -0.05211571, -0.10283093,  0.02749649,  0.00964011]])

In [18]:
assert (A.shape==(5,1))

In [20]:
a  = A.reshape(1,5)
a

array([[ 0.11942128, -0.53079616, -1.04732835,  0.28005047,  0.09818404]])

In [26]:
x = np.random.rand(8,1)
x.reshape(2,2,2)

array([[[0.85906179, 0.14767168],
        [0.99272028, 0.13490535]],

       [[0.94882761, 0.53688651],
        [0.8565314 , 0.7513359 ]]])